rootProject.name = "java-playground"
include("basic")
include("spring-aop")
include("spring-validation")
include("spring-filter")
include("spring-interceptor")
include("spring-async")
include("spring-batch")
include("modern-java")
include("effective-java")
include("spring-data-jpa")
