spring:
  application:
    name: spring-data-jpa

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jpa_test
    username: root
    password: example
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: pool_jpa
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        hbm2ddl:
          auto: update
        auto_quote_keyword: true